return {
    SPLASH = {
        HEX('FFB7B2'),
        HEX('A4D4FF')
    },
    MULT = HEX('FFB7B2'),
    CHIPS = HEX('A4D4FF'),
    PLASMA = HEX('E6C5E8'),
    MONEY = HEX('F9D7A5'),
    XMULT = HEX('FFB7B2'),
    FILTER = HEX('FFC085'),
    BLUE = HEX('A4D4FF'),
    RED = HEX('FFB7B2'),
    GREEN = HEX('A8D9C4'),
    PALE_GREEN = HEX('B0D3BC'),
    ORANGE = HEX('FFDAA5'),
    IMPORTANT = HEX('FFC085'),
    GOLD = HEX('F5DC9A'),
    YELLOW = HEX('FFFFB3'),
    CLEAR = HEX('00000000'), 
    WHITE = HEX('FFFFFF'),
    PURPLE = HEX('C9A6D1'),
    GREY = HEX('C6D0D1'),
    CHANCE = HEX('A8D9C4'),
    JOKER_GREY = HEX('E0E7F2'),
    VOUCHER = HEX('E1A792'),
    BOOSTER = HEX('B4BDEA'),
    ETERNAL = HEX('E9A7B8'),
    PERISHABLE = HEX('A5B6DF'),
    RENTAL = HEX('D9C08C'),
    DYN_UI = {
        MAIN = HEX('374244'),
        DARK = HEX('374244'),
        BOSS_MAIN = HEX('374244'),
        BOSS_DARK = HEX('374244'),
        BOSS_PALE = HEX('374244')
    },
    SO_1 = {
        Hearts = HEX('F37A93'),
        Diamonds = HEX('F49775'),
        Spades = HEX('8A85D1'),
        Clubs = HEX('75B6B4'),
    },
    SO_2 = {
        Hearts = HEX('F7A39F'),
        Diamonds = HEX('E8B84D'),
        Spades = HEX('A491E4'),
        Clubs = HEX('75BEEF'),
    },
    UI = {
        TEXT_LIGHT = HEX('FFFFFF'),
        TEXT_DARK = HEX('BAC8C9'),
        TEXT_INACTIVE = HEX('D5D5D7'),
        OUTLINE_LIGHT = HEX('E5E5E5'),
        OUTLINE_LIGHT_TRANS = HEX('E5E5E599'),
        OUTLINE_DARK = HEX('B6D5D5'),
        TRANSPARENT_LIGHT = HEX('F2F2F266'),
        TRANSPARENT_DARK = HEX('55555566'),
        HOVER = HEX('AAAAAA88'),
    },
    SET = {
        Default = HEX('E3E9E9'),
        Enhanced = HEX('E3E9E9'),
        Joker = HEX('8A989B'),
        Tarot = HEX('8A989B'),
        Planet = HEX('8A989B'),
        Spectral = HEX('8A989B'),
        Voucher = HEX('8A989B'),
    }, 
    SECONDARY_SET = {
        Default = HEX('C8DBDBFF'),
        Enhanced = HEX('B7C1EEFF'),
        Joker = HEX('A8B8BC'),
        Tarot = HEX('C8A1D6'),
        Planet = HEX('89D9E7'),
        Spectral = HEX('89ADFF'),
        Voucher = HEX('FF9A6B'),
        Edition = HEX('95D2B8'),
    }, 
    RARITY = {
        HEX('A4D4FF'),
        HEX('A8D9C4'),
        HEX('FFB7B2'),
        HEX('D7A6D7')
    },
    BLIND = {
        Small = HEX('A7D8C2'),
        Big = HEX('A7D8C2'),
        Boss = HEX('E9A48A'),
        won = HEX('BAC8C9')
    },
    HAND_LEVELS = {
        HEX('F2F2F2'),
        HEX('C3D5FF'),
        HEX('A6EFC8'),
        HEX('FAE3B5'), 
        HEX('FFD6A8'), 
        HEX('FFA39D'),
        HEX('E0C8FF')
    }
}
